:card_file_box: [#26] added organisation model
GeneriekPublicatiePlatformWoo/registratie-component pull request #78
Opened 2024-10-18 09:13 UTC by bart-maykin

Partially Fixes #26

**Changes**

- Added Organisation model
- Changed `InformationCategoryOrigins` constant name to `Origins`

2024-10-18 10:25 UTC, bart-maykin commented on src/woo_publications/metadata/models.py
> +        default=False,
Change to True

2024-10-22 19:35 UTC, sergei-maertens requested changes

2024-10-22 19:35 UTC, sergei-maertens commented on src/woo_publications/metadata/models.py
> +CUSTOM_ORGANIZATION_URL_PREFIX = "https://generiek-publicatieplatform.woo/organization/"
```suggestion
CUSTOM_ORGANISATION_URL_PREFIX = "https://generiek-publicatieplatform.woo/organisation/"
```
Let's stick to consistent British English spelling. The model name is correct.

2024-10-22 19:35 UTC, sergei-maertens commented on src/woo_publications/metadata/models.py
> +        choices=Origins.choices,
I don't think this goes like that, there is not a single value list for organisations, but a union of multiple lists that need to be imported. The `oorsprong` should reflect this. This is pointed to from the ticket: https://github.com/GeneriekPublicatiePlatformWoo/registratie-component/issues/8#issuecomment-2325940935

2024-10-23 12:24 UTC, merged